### ISSUE TITLE
Physical BUG

### ISSUE THREAD

**Issue by LigaLiao** [benikabocha/saba#10]
![qq 20180602154107](https://user-images.githubusercontent.com/12179645/40872276-243e2c02-667e-11e8-8d94-4006fb5d66fb.png)

![qq 20180602154056](https://user-images.githubusercontent.com/12179645/40872270-174c300c-667e-11e8-8462-6c28ba3dc5f3.png)

YYB Hatsune Miku_10th_v1.02

**Comment by benikabocha** [comment]
This issue is fixed.

Thanks for contributing.

**Comment by LigaLiao** [comment]
もう一つ問題がある。
sabaはほとんどのモデルを使っている間、物理的な表現が良好だった、
でもこのYYB Mikuのスカートは剛体を通すそして剛体に陥るの状况がある。 
![qq 20180607144404](https://user-images.githubusercontent.com/12179645/41092182-e7cbeace-6a7a-11e8-9c75-b851aee8f26d.png)

**Comment by LigaLiao** [comment]
[mmdDIVA_hand in hand.zip](https://github.com/benikabocha/saba/files/2087774/mmdDIVA_hand.in.hand.zip)

問題の発生はMIKUが左右走っている時

**Comment by benikabocha** [comment]
Bullet Physics のシミュレーション設定を編集できるようにしました。
FPS を 240.0 に設定すると改善するかもしれません。

![image](https://user-images.githubusercontent.com/24975344/41202287-c43d776a-6d01-11e8-8cfd-49a9d8948538.png)

こちらの環境では、FPS を 240.0 に設定したところ問題は発生しなくなりました。
