### ISSUE TITLE
how it can support loop animation?

### ISSUE THREAD

**Issue by FinchZ** [benikabocha/saba#12]
i try to modify vmdAnimation.cpp to check if the animation has ended,and then replay it...but the key frame at the last index seems not the end of the animation.....can you give me a example or ....release a new version.thanks.   : - )

**Comment by FinchZ** [comment]
but why you use binary_search to find the next key frame not to use a value to store it?
when update ,it's a waste of resource..

**Comment by benikabocha** [comment]
I considered the possibility of jumping to any frame.
I will improve VMDAnimation.
