### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by FinchZ** [benikabocha/saba#13]
https://github.com/benikabocha/saba/blob/899381fb4d7e60747b2de2c36b16f1a1a1bdff82/src/Saba/Model/MMD/VMDAnimation.cpp#L398

1.0f / 30.0f
should be changed to 
1.0f / frameCount

**Comment by benikabocha** [comment]
This is not a bug.
The frameCount of SyncPhysics is the time it takes to reach the target's pose.
For example, SyncPhysics (60) will be 2 seconds.
