### ISSUE TITLE
the order of rotation?

### ISSUE THREAD

**Issue by zhouhang95** [benikabocha/saba#14]
why not yaw-pitch-roll?

**Comment by zhouhang95** [comment]
src/Saba/Model/MMD/MMDCamera.cpp
```
		rot = glm::rotate(rot, cam.m_rotate.y, glm::vec3(0, 1, 0));
		rot = glm::rotate(rot, cam.m_rotate.z, glm::vec3(0, 0, -1));
		rot = glm::rotate(rot, cam.m_rotate.x, glm::vec3(1, 0, 0));
```

**Comment by benikabocha** [comment]
Question of rotation order?

It is VMD specification.
https://blog.goo.ne.jp/torisu_tetosuki/e/bc9f1c4d597341b394bd02b64597499d

I also confirmed that it works the same as MMM.

**Comment by zhouhang95** [comment]
tks
