### ISSUE TITLE
Deformed joints

### ISSUE THREAD

**Issue by shoedrip** [benikabocha/saba#16]
![Screenshot from 2020-06-03 00-08-54](https://user-images.githubusercontent.com/28990541/83574788-6f251000-a52e-11ea-8fca-c6e7592d6e6e.png)

This might be related to #8 

[Motion](https://mega.nz/file/OGpUlAbQ#Z_vMdtz7daAKXPI9HnEGFE0b-_HWuGGbzo-7z9kB_Ls)
[Model](https://www.deviantart.com/users/outgoing?https://www.dropbox.com/s/q0bk5t8fxk1wfs8/Meltdown%20R.K.%20Mix.zip?dl=1)

**Comment by shoedrip** [comment]
According to bisect, this regression happened in [ce99d5](https://github.com/benikabocha/saba/commit/ce99d575ed895294eae1dac1b18a3019bc4ec1b4)

**Comment by benikabocha** [comment]
Thank you.
I will try to fix it.
