### ISSUE TITLE
Transparent Window gets a pink window

### ISSUE THREAD

**Issue by superowner** [benikabocha/saba#21]
Not a Transparent Window but run fine.I don't know what's happen!
![Snipaste_2021-07-24_02-06-26](https://user-images.githubusercontent.com/15080614/126853646-586b16b2-2eb9-4f9d-967a-db7f302a15a1.png)
Windows 10x64 Home 19042.1110,VS2019

**Comment by benikabocha** [comment]
The GLFW version may be old.
Can you check with the latest version of GLFW?

**Comment by superowner** [comment]
> The GLFW version may be old.
> Can you check with the latest version of GLFW?

thx for your answer, I use glfw-3.3.4 and glfw-3.4(latest), but all are pink.Now I wanna try some old ver...

**Comment by benikabocha** [comment]
I had the same problem using glfw-3.3.4.

Please use glfw-3.3.2.

**Comment by benikabocha** [comment]
Color key has been removed from GLFW. 

https://github.com/glfw/glfw/issues/1512

**Comment by superowner** [comment]
> Color key has been removed from GLFW.
> 
> [glfw/glfw#1512](https://github.com/glfw/glfw/issues/1512)

Yes, form glfw-3.3.3 to now are failed，now I rollback to glfw-3.3.2(it's ok)

**Comment by benikabocha** [comment]
Try to add a color key to the sample.
