### ISSUE TITLE
Segfault when loading model

### ISSUE THREAD

**Issue by brainrom** [benikabocha/saba#33]
For some models, Saba segfaults when doing `PMXModel::InitializeAnimation()`. `m_ikTarget` isn't initialized, and program finally crashes at `MMDIkSolver::SolveCore()`. Same behavior in saba_view, examples and direct library usage.
I could post an example model, which I try to load.

**Comment by benikabocha** [comment]
Thanks. Could you please send me that model?

**Comment by brainrom** [comment]
Sure. PM'ed the model via e-mail. I'm not 100% sure, if this model are absolutely correct, but anyway it's better to throw an error, than segfault.

**Comment by benikabocha** [comment]
The model contained a wrong IK target. In such cases, an error message is displayed.

**Comment by brainrom** [comment]
Thank you. This fixed wrong IK target issue. Also found a models with some morphs loading issues.

**Comment by benikabocha** [comment]
Do you have any other incorrect models? Send that model to me and I will check it out.

**Comment by brainrom** [comment]
PMed via e-mail.

**Comment by benikabocha** [comment]
Check for loops in bone hierarchies.

**Comment by brainrom** [comment]
Thank you! This helps. But I discovered one more bug and finally managed to fix it on my own, sent the PR #34 
I have tested all MMD models that I have, and all loaded successfully, so consider that the issue is closed.
