### ISSUE TITLE
The name of the struct is misspelled.

### ISSUE THREAD

**Issue by qian-o** [benikabocha/saba#44]
![image](https://github.com/benikabocha/saba/assets/84434846/e68e7bbb-f92d-4ea5-af44-535126437b6e)

**Comment by qian-o** [comment]
![image](https://github.com/benikabocha/saba/assets/84434846/7fe8403e-2654-4ee4-b3c1-eb31275a1340)

**Comment by benikabocha** [comment]
Thank you.
I will fix its.

**Comment by qian-o** [comment]
![image](https://github.com/benikabocha/saba/assets/84434846/a576317a-f636-48d5-ada5-9a9cb4326df7)
This piece of code can be simplified.

**Comment by qian-o** [comment]
I've been closely following the code of this repository recently and have learned a lot from it. However, I've also noticed many details in the code that could be problematic. I hope this doesn't bother you. At the same time, I hope that more people can get to know and learn from this project.
![e654e1c2a9859a6cce2413b5a454d498](https://github.com/benikabocha/saba/assets/84434846/c40c361c-2dbc-4600-a6ea-2b8b71b1610f)
