### ISSUE TITLE
IKの動作はエラーがあります

### ISSUE THREAD

**Issue by LigaLiao** [benikabocha/saba#5]
<img src="https://public.lightpic.info/thumb/E161_59D20E330.jpg" border="0">

**Comment by LigaLiao** [comment]
すべてのikあるの vmdは問題 がある

**Comment by LigaLiao** [comment]
アニメ　終わりまでじっくり見て見て ください。

**Comment by benikabocha** [comment]
I tried it with this sample.
http://3d.nicovideo.jp/works/td14712
http://3d.nicovideo.jp/works/td8608

- pmx file
Alicia_solid.pmx
プロ生ちゃん.pmx

- vmd file
2分ループステップ1.vmd

I played to the end of the animation, but the problem could not be reproduced.
It is difficult to reproduce the IK problem.
Is there any other information?

**Comment by LigaLiao** [comment]
すみません！
多くのテストの後  問題の原因は私が誤ってコードを変更しました。

でも 小さなIKのエラーを発見した，私はあなたのメールに VMD を送った。

**Comment by benikabocha** [comment]
メールを送っていただき、ありがとうございます。
IKの問題が再現しました。

Thank you for sending me an email.
The IK problem was reproduced.

**Comment by LigaLiao** [comment]
こちらこそありがとうございます
私はこのsabaからたくさん勉強しました。

**Comment by benikabocha** [comment]
ほかのツールで試してみました。
I tried it with other tools.

- PmxEditor_0232c
![pmx_editor](https://user-images.githubusercontent.com/24975344/31180216-012181f2-a959-11e7-82a9-5c9e84afeaf6.png)

- MMM v1271
![mmm](https://user-images.githubusercontent.com/24975344/31180237-0cf01e4e-a959-11e7-99e9-2a0845ffb705.png)

- saba
![saba](https://user-images.githubusercontent.com/24975344/31180242-145d818a-a959-11e7-809c-74c59dfde4d2.png)

saba の IK Solver は PmxEditor に似ています。
The saba IK solver is similar to PmxEditor.

アニメーションを編集するのが良いかもしれません。
I recommend editing the animation (vmd file).

**Comment by LigaLiao** [comment]
分かった ありがとう
