### ISSUE TITLE
SDEF and QDEF bones support?

### ISSUE THREAD

**Issue by lieff** [benikabocha/saba#8]
I found that such bones is not supported, but widely used.
I take quick look and found implementation of this bones here:
https://github.com/VegetableAvenger/SEngine
https://github.com/newpolaris/Mikudayo
https://github.com/hkrn/MMDAI
https://github.com/r1cebank/ofxMMDX

**Comment by benikabocha** [comment]
I'll check it out.

**Comment by lieff** [comment]
Thanks)

**Comment by benikabocha** [comment]
Mikudayo used Dual Quaternion to process SDEF.
Saba did the same way.

However, the original SDEF uses other parameters.
Therefore, when SDEF is used, a warning is displayed.

**Comment by lieff** [comment]
Yes, looks like I wrong about Mikudayo. I did not notice that SDEF C/R0/R1 params unused.
Same about others, I can see it's stored https://github.com/VegetableAvenger/SEngine/blob/master/libVisualizationAvatar/vaMemory.cpp#L633, but can't find if it's used :(

**Comment by zhouhang95** [comment]
A better way to approximate SDEF interpolation using blender armatures
https://github.com/powroupi/blender_mmd_tools/issues/162

**Comment by benikabocha** [comment]
Thank you.
I will try it.
