### ISSUE TITLE
simple_mmd_viewer_dx11でのエラー

### ISSUE THREAD

**Issue by sakya-suzuki** [benikabocha/saba#9]
お世話になっております
新しい更新が入ったと思って最新をpullさせていただきましたが
simple_mmd_viewer_dx11にて以下のエラーが出ております
エラー	C2275	'IDXGIDevice1': この型は演算子として使用できません	simple_mmd_viewer_dx11	D:\prog\pmx\saba-master\example\simple_mmd_viewer_dx11.cpp	1397	

どうやらstructとして判別しているらしく->が使い得ないみたいです
	hr = m_device->QueryInterface<IDXGIDevice1>(&dxgi);
Cmakeでは前回と同様にVs2015と2017を使っていますが両バージョンにて同様のエラーで出ております
なにか設定するものはありますでしょうか？
ご教授お願いいたします

**Comment by benikabocha** [comment]
報告ありがとうございます。

Unknwnbase.h が読み込まれなくなったのが原因かと思います。
ComPtr::CopyTo に置き換えました。
